# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: hemangsk@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Shendy's Blog</h1><h3>A blog for dev stuff!</h3>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devahmedshendy.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
